services: 
  client-react-vite: 
    image: client-react-vite
    build: 
      context: ../05-example-web-application/client-react
      dockerfile: ../../06-building-container-images/client-react/Dockerfile.4
    init: true 
    volumes: 
      - ${PWD}/client-react/vite.config.js:/usr/src/app/vite.config.js 
    networks: 
      - frontend 
    ports: 
      - 5173:5173
  client-react-nginx: 
    image: client-react-nginx 
    build: 
      context: ../05-example-web-application/client-react 
      dockerfile: ../../06-building-container-images/client-react/Dockerfile.5
    init: true 
    networks: 
      - frontend
    ports: 
      - 80:8080 
    restart: unless-stopped 
  api-node: 
    image: api-node
    build: 
      context: ../05-example-web-application/api-node
      dockerfile: ../../06-building-container-images/api-node/Dockerfile.8
    init: true 
    depends_on:
      - db
    networks: 
      - frontend
      - backend 
    ports: 
      - 3000:3000 
    restart: unless-stopped 
  api-golang: 
    image: api-golang
    build: 
      context: ../05-example-web-application/api-golang
      dockerfile: ../../06-building-container-images/api-golang/Dockerfile.6
    init: true 
    depends_on:
      - db 
    ports: 
      - 8080:8080
    restart: unless-stopped 
    networks: 
      - frontend
      - backend
  db: 
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks: 
      - backend 
    restart: unless-stopped 
    ports: 
      - 5432:5432 
    volumes: 
      - pgdata:/var/lib/postgresql/data 
volumes: 
  pgdata: 
networks: 
  frontend: 
  backend: